#%RAML 1.0
title: "Title3"

securitySchemes:
  Security3:
    type:
  Security3_1:
    type:
  
traceability:
  Trace1
types:
  aschema: !include schema/aschema.json

/resource3:
  description: "desc3"
  post:
    responses:
      205:
        body:
          application/json:
            schema: 
      203:
        body:
          application/json:
            schema: 
